name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.34.0

      - name: Cache Deno Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.json') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Clean and Initialize Lockfile
        run: |
          rm -f deno.lock
          deno cache --reload mod.ts

      - name: Generate Lockfile
        run: |
          deno cache --lock=deno.lock --lock-write mod.ts

      - name: Verify Dependencies
        run: |
          deno cache mod.ts

      - name: Lint Code
        run: deno lint

      - name: Prepare Coverage Directory
        run: mkdir -p cov

      - name: Run Tests
        run: deno test --allow-read --allow-env --allow-write --coverage=cov

      - name: Generate Coverage Report
        run: deno coverage cov --lcov > cov.lcov

      - name: Save Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            cov.lcov
            deno.lock
          if-no-files-found: warn