name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Initialize Dependencies
        run: |
          rm -f deno.lock
          deno cache --reload mod.ts
          deno cache --lock=deno.lock --lock-write mod.ts
          deno cache --lock=deno.lock mod.ts

      - name: Cache Deno Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/deno
            ~/.deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.json', '**/deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Clean Test Environment
        run: |
          # Clean temp and coverage directories
          rm -rf /tmp/test_tmp /tmp/deno_dir coverage cov tests/fixtures/dynamic locales
          deno task test:clean
          
          # Create necessary directories
          mkdir -p /tmp/test_tmp /tmp/deno_dir coverage cov tests/fixtures/{dynamic,generated} locales
          chmod -R 777 /tmp/test_tmp /tmp/deno_dir coverage cov tests/fixtures locales

      - name: Setup Test Data
        run: |
          # Initialize locale file
          cat > locales/en.json << 'EOF'
          {
            "available_commands": "Available Commands:",
            "use_help": "Use '{command} --help' for more information",
            "command_not_found": "Command \"{command}\" not found.",
            "missing_required_flag": "Missing required flag: {flag}",
            "invalid_flag_value": "Invalid value for flag '{flag}': {value}",
            "command": "Command",
            "options": "Options",
            "help_text": "Shows help information",
            "default": "default",
            "subcommand_not_found": "Subcommand \"{subcommand}\" not found.",
            "no_command_provided": "No command provided.",
            "error": "Error: {message}",
            "debug": "Debug: {message}",
            "info": "Info: {message}",
            "warning": "Warning: {message}"
          }
          EOF
          
          # Cache test files
          deno task test:cache

      - name: Verify Formatting
        run: deno task fmt:check

      - name: Run Linter
        run: deno task lint

      - name: Run Tests with Coverage
        timeout-minutes: 15
        env:
          DENO_DIR: /tmp/deno_dir
          TMPDIR: /tmp/test_tmp
          TEST_MODE: ci
          NO_COLOR: true
          DEBUG: true
          LOCALE: en
          DENO_PERMISSIONS: allow-all
        run: |
          deno task test
          
          # Copy coverage files
          cp -R coverage/* cov/ || true
          
          # Generate coverage reports
          deno coverage coverage --lcov > coverage.lcov || true
          deno coverage cov --lcov > cov.lcov || true
          
          # Verify coverage files
          if [ ! -f coverage.lcov ] && [ ! -f cov.lcov ]; then
            echo "Error: Failed to generate coverage report"
            exit 1
          fi

      - name: Build Binaries
        run: |
          # Ensure dist directory exists
          mkdir -p dist
          
          # Build all targets
          deno task build:all
          
          # Verify build outputs
          if [ ! -f dist/stega-linux ] || [ ! -f dist/stega-windows.exe ] || [ ! -f dist/stega-macos ]; then
            echo "Error: Missing build artifacts"
            ls -la dist/
            exit 1
          fi

      - name: Upload Coverage Results
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: |
            cov.lcov
            coverage.lcov
            cov/
            coverage/
          retention-days: 14
          compression-level: 9
          if-no-files-found: error

      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/stega-linux
            dist/stega-windows.exe
            dist/stega-macos
          retention-days: 14
          compression-level: 6
          if-no-files-found: error

      - name: Upload Lockfile
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: deno-lockfile
          path: deno.lock
          retention-days: 7
          compression-level: 9
          if-no-files-found: warn

      - name: Cache Cleanup
        if: always()
        run: deno task cache:clean