name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.34.0

      - name: Cache Deno Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.json', '**/deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Validate or Regenerate Lockfile
        run: |
          if [ ! -f deno.lock ]; then
            echo "Lockfile missing, regenerating..."
            deno cache --lock=deno.lock --reload mod.ts
          else
            deno cache --lock=deno.lock mod.ts
          fi

      - name: Lint Code
        run: deno lint

      - name: Prepare Coverage Directory
        run: mkdir -p cov

      - name: Run Tests
        run: deno test --allow-read --allow-env --allow-write --coverage=cov

      - name: Generate Coverage Report
        run: deno coverage cov --lcov > cov.lcov

      - name: Save Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: cov.lcov
          if-no-files-found: warn