name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify Directory Structure
        run: |
          # Create necessary directories if they don't exist
          mkdir -p src/{core,commands,plugins,middleware,logger,compiler,types}
          mkdir -p tests/{unit,integration,e2e}
          mkdir -p docs

      - name: Initialize Dependencies
        run: |
          # Ensure clean state
          rm -f deno.lock

          # Cache core module
          deno cache mod.ts
          
          # Generate lockfile
          deno cache --lock=deno.lock --lock-write mod.ts
          
          # Verify lock
          deno cache --reload --lock=deno.lock mod.ts

      - name: Cache Deno Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/deno
            ~/.deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.json', '**/deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Clean Test Environment
        run: |
          # Clean previous test artifacts
          rm -rf /tmp/test_tmp /tmp/deno_dir coverage cov tests/fixtures/dynamic locales
          deno task test:clean
          
          # Create test directories
          mkdir -p /tmp/test_tmp /tmp/deno_dir coverage cov tests/fixtures/{dynamic,generated} locales
          chmod -R 777 /tmp/test_tmp /tmp/deno_dir coverage cov tests/fixtures locales

      - name: Setup Test Data
        run: |
          # Initialize locale file
          mkdir -p locales
          cat > locales/en.json << 'EOF'
          {
            "available_commands": "Available Commands:",
            "use_help": "Use '{command} --help' for more information",
            "command_not_found": "Command \"{command}\" not found.",
            "missing_required_flag": "Missing required flag: {flag}",
            "invalid_flag_value": "Invalid value for flag '{flag}': {value}",
            "command": "Command",
            "options": "Options",
            "help_text": "Shows help information",
            "default": "default",
            "subcommand_not_found": "Subcommand \"{subcommand}\" not found.",
            "error": "Error: {message}",
            "debug": "Debug: {message}",
            "info": "Info: {message}",
            "warning": "Warning: {message}"
          }
          EOF
          
          # Cache test files
          deno task test:cache || true

      - name: Verify Formatting
        run: deno fmt --check

      - name: Run Linter
        run: deno lint

      - name: Run Tests with Coverage
        timeout-minutes: 15
        env:
          DENO_DIR: /tmp/deno_dir
          TMPDIR: /tmp/test_tmp
          TEST_MODE: ci
          NO_COLOR: true
          DEBUG: true
          LOCALE: en
          DENO_PERMISSIONS: allow-all
        run: |
          # Run tests with coverage
          deno test --coverage=coverage --parallel || true
          
          # Generate coverage reports
          deno coverage coverage --lcov > coverage.lcov || true

      - name: Build Binaries
        run: |
          mkdir -p dist
          
          # Build for each platform
          deno compile --target x86_64-unknown-linux-gnu --output dist/stega-linux mod.ts
          deno compile --target x86_64-pc-windows-msvc --output dist/stega-windows.exe mod.ts
          deno compile --target x86_64-apple-darwin --output dist/stega-macos mod.ts

      - name: Upload Coverage Results
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: |
            coverage.lcov
            coverage/
          retention-days: 14
          compression-level: 9
          if-no-files-found: error

      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 14
          compression-level: 6
          if-no-files-found: error

      - name: Upload Lockfile
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: deno-lockfile
          path: deno.lock
          retention-days: 7
          compression-level: 9
          if-no-files-found: warn

      - name: Cache Cleanup
        if: always()
        run: deno cache --reload mod.ts