name: Publish

on:
  push:
    tags: ["v*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup Test Environment
        run: |
          # Create all required directories with proper permissions
          sudo mkdir -p /tmp/test_tmp /tmp/deno_dir
          sudo chmod -R 777 /tmp/test_tmp /tmp/deno_dir

          mkdir -p tests/fixtures/{templates,plugins,locales,tmp,dynamic}
          chmod -R 777 tests/fixtures

          # Initialize test data
          deno task test:init

      - name: Initialize Dependencies
        run: |
          # Clear and reinitialize cache
          rm -rf .deno
          mkdir -p .deno

          # Cache dependencies with lockfile
          deno cache --lock=deno.lock --lock-write mod.ts

          # Cache test files
          find tests -name "*.ts" -type f -exec deno cache {} +

          # Force cache plugins directory
          mkdir -p tests/fixtures/plugins
          find tests/fixtures/plugins -name "*.ts" -type f -exec deno cache {} + || true

      - name: Run Tests with Coverage
        env:
          DENO_DIR: .deno
          TMPDIR: /tmp/test_tmp
          TEST_MODE: ci
          NO_COLOR: true
          DEBUG: true
          PRESERVE_TEST_FILES: "1"
          DENO_COMMAND_TIMEOUT: "60000"
        run: |
          # Create coverage directory
          mkdir -p coverage

          # Run tests while preserving generated files
          deno test --allow-all --coverage=coverage --parallel || exit 1

          # Ensure coverage directory permissions
          sudo chown -R $USER:$USER coverage

          # Cache any dynamically generated test files
          find tests/fixtures -name "*.ts" -type f -exec deno cache {} + || true

          # Allow file system to sync
          sleep 5

          # Generate coverage with increased timeout
          deno coverage coverage --lcov > coverage.lcov

      - name: Build Binaries
        run: |
          mkdir -p dist
          deno compile --target x86_64-unknown-linux-gnu --output dist/stega-linux mod.ts
          deno compile --target x86_64-pc-windows-msvc --output dist/stega-windows.exe mod.ts
          deno compile --target x86_64-apple-darwin --output dist/stega-macos mod.ts

      - name: Run Verification
        run: deno task verify

      - name: Verify Package
        run: deno publish --dry-run

      - name: Publish to JSR
        if: startsWith(github.ref, 'refs/tags/v')
        run: deno publish
